### ISSUE TITLE
icons: use new updates to libraries

### ISSUE THREAD

**Issue by reez** [reez/WalletUI#36]
**Is your feature request related to a problem? Please describe.**
Bitcoin Icons and Hardware illustrations have been updated and added GitHub repos.

**Describe the solution you'd like**
Use the GitHub repos
https://github.com/GBKS/bitcoin-hardware-illustrations
https://github.com/BitcoinDesign/Bitcoin-Icons

**Additional context**

- [ ] Do I need to remove a layer on all new icons like I did with Figma files?
- [ ] Remove old bitcoin icons
- [ ] Remove old hardware icons
- [ ] Add new bitcoin icons
- [ ] Add new hardware icons
- [ ] Make sure Previews still work (old icons had 3 sizes, make sure to constrain `Image` size now)
- [ ] Make sure MyMattress still works (dot icons might not be in bitcoin/hardware icons)

**Comment by GBKS** [comment]
Would it be easier for you if the icons were available as npm libraries (or via some other package management system)?

**Comment by reez** [comment]
Thats a good question and good potential idea. The package management system for Swift would be [Swift Package Manager](https://swift.org/package-manager/). It might be more involved than npm, so just holler at me if its something you want to test out in the future and I can help out in any way.
