### ISSUE TITLE
icons: use sf symbols or spec icons?

### ISSUE THREAD

**Issue by reez** [reez/WalletUI#4]
**Is your feature request related to a problem? Please describe.**
Apple has SF Symbols available [HIG](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/)

**Describe the solution you'd like**
Mix and match use of SF Symbols with Figma file icons

**Additional context**
_SF Symbols provides a set of over 2,400 consistent, highly configurable symbols you can use in your app. Apple designed SF Symbols to integrate seamlessly with the San Francisco system font, so the symbols automatically ensure optical vertical alignment with text in all weights and sizes_

**Comment by johnsBeharry** [comment]
Good question. Raises a few more @GBKS @ConorOkus

- Is there a need for consistency between android and iOS (and potentially desktop)?
- How to deal with bitcoin specific icons which may not be in the icon font?
- How to allow projects to swap in their own replacement icons?

@Bosch-0 has also been working on some of these bitcoin specific icons - https://github.com/Bosch-0/Bitcoin-Icons

**Comment by Bosch-0** [comment]
Just wrote up a short collaboration proposal for that project - https://github.com/BitcoinDesign/Meta/issues/72

**Comment by GBKS** [comment]
May want to review the [license agreement](https://developer.apple.com/terms/) for any potential issues.
![image](https://user-images.githubusercontent.com/695901/107642456-37ea2f80-6c75-11eb-93d1-506fa09184b2.png)

For the Figma file, I think the icons need to be unique symbols in the kit, as it should not be specific to Apple operating systems. But since this code library is specific to Apple operating systems, maybe you can default to SF Symbols here, and then complement it with custom icons as needed?

TBH, I am sticking pretty closely to Apple-style icons anyways, so they probably go pretty well with SF Symbols.

**Comment by reez** [comment]
> May want to review the [license agreement](https://developer.apple.com/terms/) for any potential issues.
> ![image](https://user-images.githubusercontent.com/695901/107642456-37ea2f80-6c75-11eb-93d1-506fa09184b2.png)
> 
> For the Figma file, I think the icons need to be unique symbols in the kit, as it should not be specific to Apple operating systems. But since this code library is specific to Apple operating systems, maybe you can default to SF Symbols here, and then complement it with custom icons as needed?
> 
> TBH, I am sticking pretty closely to Apple-style icons anyways, so they probably go pretty well with SF Symbols.

Cool, I implemented mix and match between SF Symbols and the Bitcoin Kit Figma icons. I’m defaulting to using SF Symbols, but if it is specific to the Bitcoin Kit Figma I complement by using the Bitcoin Kit Figma icons.

(Happy to know you’re sticking closely to the Apple-style icons so the SFSymbols and BitcoinKit icons look the same.)

Sounds like we’re on the same page with those things ✅

**Comment by reez** [comment]
Going to close this out, created #25 to clean up unneeded icons after this discussion confirmed using a mix of native and Figma icons.
