### ISSUE TITLE
Contributing with UIKit components

### ISSUE THREAD

**Issue by danielnordh** [reez/WalletUI#65]
Hi, I've been involved in the Bitcoin Design community since the start and am currently trying to build an open source 'daily spending wallet' based on the same concept in the Bitcoin Design Guide. Some of my work so far can be found [here](https://github.com/bdgwallet).

I am going to try to emulate the UI components as closely as possible, and this repo is a good start with the colors and icons files.
The examples are also useful, but what I am hoping to do is break those screens down to individual components that can be available in a 'components.swift' file, alongside the colors and icons files.

A couple of questions on the setup of the repo:

- What files are included in the package library imported to an app that uses this repo, only the colors and icons files?
- If I add a new 'components.swift file', will that automatically get included in the package or do I need to specify that somewhere?

Let me know if you have any other thoughts on what I'm trying to do.

**Comment by reez** [comment]
Hi! Looks like you are doing some good work!

Breaking down the screens into individual components is definitely something that should be included in an SDK like this at some point in its evolution. I'm happy you are going to try it out and happy to help you in whatever way you need me as a sounding board for any of it.

> What files are included in the package library imported to an app that uses this repo, only the colors and icons files?

At the moment if someone creates a project (for example called "TestWalletUI") and adds the `WalletUI` package to the project, they will have access to everything in the `WalletUI` package: `Colors.swift`, `Images.swift`, Image assets, Examples, etc.

<img width="1054" alt="Screen Shot 2022-09-08 at 8 35 27 AM" src="https://user-images.githubusercontent.com/6657488/189136244-375b08d2-2b45-4b78-b576-223a50242888.png">

> If I add a new 'components.swift file', will that automatically get included in the package or do I need to specify that somewhere?

Yes it will automatically be included in the package if you add a new `Components.swift` file. And then structurally that file can just be put next to `Colors.swift` and `Images.swift` files like `.../WalletUI/Sources/WalletUI/Components.swift`.

Holler at me if I missed anything, something needs more clarity, if you ever want any extra explanation of the thought behind how this was structured, or essentially anything that will help you feel confident and clear moving forward with the work you are doing and what is important to you-

**Comment by danielnordh** [comment]
Please see #66 for the first contribution.

**Comment by reez** [comment]
Looks great, really well done and thanks for adding to the README as a part of the contribution!  Great code, great contribution.
