### ISSUE TITLE
button: renaming

### ISSUE THREAD

**Issue by reez** [reez/WalletUI#74]
Rectangle buttons existed but I just added Capsule buttons (which I hope is a nice addition), what do you think about me renaming the Rectangle buttons? 

I named the capsule buttons `BitcoinCapsuleFilled` and `BitcoinCapsuleOutlined` with the Rectangle buttons in mind so that I could possibly rename those to `BitcoinRectangleFilled` and `BitcoinRectangleOutlined` possibly. Thoughts @danielnordh ?

Also I didn't make a `BitcoinCapsulePlain` button because `BitcoinPlain` doesn't really have a border shape anyway from what I can tell, let me know if I'm missing something though.

<img width="1202" alt="Screenshot 2023-08-24 at 8 47 32 AM" src="https://github.com/reez/WalletUI/assets/6657488/c4c18962-ff98-48b0-92a9-4117f4b2f9df">

**Comment by reez** [comment]
> No complaints about renaming, I took the names from the Figma file to match what was going on there.
> 
> One thought however: The BitcoinFilled and BitcoinOutlined buttons do have optional radius parameters which would enable you to make the Capsule style. Not sure if that was clear, or changes anything with your thinking in case you want just highlight that more in the readme for people wanting the capsule style.

I think my only thinking on it was just the difference between the `cornerRadius` on `BitcoinFilled` expects a `CGFloat` that is a hardcoded value vs `BitcoinCapsuleFilled` just uses the `Capsule` shape where the corner radius is automatically chosen for someone as half the length of the rectangle’s smallest edge (benefits: always perfectly rounded, adjusts dynamically, etc). But let me know if I'm totally thinking about that wrong -or- its not enough of an upgrade/upside.

**Comment by danielnordh** [comment]
I think many people probably like/default to a capsule shape today, so not bad thinking.

One option could be to modify the existing ones with a boolean parameter `capsuleShape` (or similar) that just sets the radius to half the height? That should not be much code change.

Or maybe that is starting to overload the whole thing.

**Comment by reez** [comment]
> 
> One option could be to modify the existing ones with an optional boolean parameter `capsuleShape` (or similar) that just sets the radius to half the height? That should not be much code change.
> 


Ahhh yeah that's a nice idea, I like that. Let me mess around with that to see what it looks/feels like!

**Comment by reez** [comment]
Added a PR #76 for this
